return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "razor",
        "tsx",
        "typescript",
        "scss",
        "vim",
        "yaml",
        "go",
        "vue",
        "css",
        "templ",
        "c_sharp",
      },
    },
  },
}
